#A toggle for the global functionality of Crossbow Enchants.
Enabled = true
#A toggle for the functionality of the Flame enchantment on the crossbow.
FlameEnabled = true
#A toggle for the functionality of the Infinity enchantment on the crossbow.
InfinityEnabled = true
#A toggle for the functionality of the Power enchantment on the crossbow.
PowerEnabled = true
#A toggle for the functionality of the Punch enchantment on the crossbow.
PunchEnabled = true
#A toggle for the compatibility of Infinity and Mending on crossbows and bows.
InfinityAndMendingEnabled = true
#A toggle for the compatibility of Piercing and Multishot on crossbows.
PiercingAndMultishotEnabled = true
