# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fastest"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				pig = true
				painting = true
				item = true
				sheep = true
				chicken = true
				glow_squid = true
				squid = true
				bat = true
				creeper = true
				skeleton = true
				zombie = true
				spider = true
				cave_spider = true
				bee = true
				enderman = true
				witch = true
				villager = true
				zombie_horse = true
				iron_golem = true
				slime = true
				cat = true
				salmon = true
				cow = true
				zombie_villager = true
				cod = true
				axolotl = true
				illusioner = true
				dolphin = true
				endermite = true
				turtle = true
				rabbit = true
				drowned = true
				experience_orb = true
				tropical_fish = true
				pillager = true
				fox = true
				arrow = true
				allay = true
				area_effect_cloud = true
				armor_stand = true
				blaze = true
				block_display = true
				boat = true
				camel = true
				chest_boat = true
				chest_minecart = true
				command_block_minecart = true
				donkey = true
				dragon_fireball = true
				egg = true
				elder_guardian = true
				end_crystal = true
				ender_dragon = true
				ender_pearl = true
				evoker = true
				evoker_fangs = true
				experience_bottle = true
				eye_of_ender = true
				falling_block = true
				firework_rocket = true
				frog = true
				furnace_minecart = true
				ghast = true
				giant = true
				goat = true
				guardian = true
				hoglin = true
				hopper_minecart = true
				horse = true
				husk = true
				interaction = true
				item_display = true
				item_frame = true
				fireball = true
				leash_knot = true
				lightning_bolt = true
				llama = true
				llama_spit = true
				magma_cube = true
				marker = true
				minecart = true
				mooshroom = true
				mule = true
				ocelot = true
				panda = true
				parrot = true
				phantom = true
				piglin = true
				piglin_brute = true
				polar_bear = true
				potion = true
				pufferfish = true
				ravager = true
				shulker = true
				shulker_bullet = true
				silverfish = true
				skeleton_horse = true
				small_fireball = true
				sniffer = true
				snow_golem = true
				snowball = true
				spawner_minecart = true
				spectral_arrow = true
				stray = true
				strider = true
				tadpole = true
				text_display = true
				tnt = true
				tnt_minecart = true
				trader_llama = true
				trident = true
				vex = true
				vindicator = true
				wandering_trader = true
				warden = true
				wither = true
				wither_skeleton = true
				wither_skull = true
				wolf = true
				zoglin = true
				zombified_piglin = true
				fishing_bobber = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				iceologer = true
				ice_chunk = true
				mauler = true
				moobloom = true
				rascal = true
				tuff_golem = true
				wildfire = true
				player_illusion = true
				crab = true

			[light_sources.settings.entities.connectiblechains]
				chain_knot = true
				chain_collision = true

			[light_sources.settings.entities.doggomodoverhauled]
				doggo = true
				tennis_ball_red_entity = true
				tennis_ball_yellow_entity = true
				tennis_ball_lime_entity = true
				tennis_ball_light_blue_entity = true

			[light_sources.settings.entities.immersive_portals]
				portal = true
				nether_portal_new = true
				end_portal = true
				mirror = true
				breakable_mirror = true
				global_tracked_portal = true
				border_portal = true
				end_floor_portal = true
				general_breakable_portal = true
				loading_indicator = true

			[light_sources.settings.entities.snowrealmagic]
				snow = true

			[light_sources.settings.entities.xercapaint]
				canvas = true
				easel = true

			[light_sources.settings.entities.cozys-improved-cats]
				improved_cat = true

			[light_sources.settings.entities.dungeonnowloading]
				spawner_carrier = true
				chaos_spawner = true
				hollow = true

			[light_sources.settings.entities.cozys-improved-wolves]
				improved_wolf = true

			[light_sources.settings.entities.geologicexpansion]
				duck = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.yungscavebiomes]
				ice_cube = true
				sand_snapper = true

			[light_sources.settings.entities.wilderwild]
				crab = true
				jellyfish = true
				firefly = true
				scorched = true
				tumbleweed = true

			[light_sources.settings.entities.variantsandventures]
				gelid = true
				verdant = true
				murk = true
				thicket = true

			[light_sources.settings.entities.underground_jungle]
				jungle_zombie = true

			[light_sources.settings.entities.swampier_swamps]
				dragonfly = true
				swamp_gas = true

			[light_sources.settings.entities.levelz]
				level_experience_orb = true

			[light_sources.settings.entities.galosphere]
				spectre = true

			[light_sources.settings.entities.promenade]
				duck = true
				lush_creeper = true
				capybara = true
				sunken_skeleton = true

			[light_sources.settings.entities.hybrid-aquatic]
				barrel_jellyfish = true
				sea_cucumber = true
				starfish = true
				sea_urchin = true
				crayfish = true
				rockfish = true
				anglerfish = true
				ghost_crab = true
				piranha = true
				tetra = true
				oscar = true
				danio = true
				ratfish = true
				dragonfish = true
				dungeness_crab = true
				barreleye = true
				flower_crab = true
				lightfoot_crab = true
				carp = true
				goldfish = true
				discus = true
				fiddler_crab = true
				betta = true
				flashlight_fish = true
				horseshoe_crab = true
				tuna = true
				opah = true
				compass_jellyfish = true
				sea_nettle = true
				blue_jellyfish = true
				mahi = true
				spider_crab = true
				oarfish = true
				manta_ray = true
				sunfish = true
				stingray = true
				triggerfish = true
				moon_jellyfish = true
				fried_egg_jellyfish = true
				needlefish = true
				cauliflower_jellyfish = true
				toadfish = true
				surgeonfish = true
				mauve_stinger = true
				firefly_squid = true
				hammerhead_shark = true

			[light_sources.settings.entities.spawn]
				tuna = true
				snail = true
				ant = true
				hamster = true
				angler_fish = true

			[light_sources.settings.entities.naturalist]
				robin = true
				boar = true
				butterfly = true
				snake = true
				bluejay = true
				snail = true
				bass = true
				cardinal = true
				lizard = true
				finch = true
				bear = true
				coral_snake = true
				deer = true
				duck = true
				canary = true
				sparrow = true
				firefly = true
				catfish = true
				tortoise = true
				dragonfly = true

			[light_sources.settings.entities.betternether]
				hydrogen_jellyfish = true
				firefly = true
				naga = true
				skull = true
				flying_pig = true

			[light_sources.settings.entities.netherdepthsupgrade]
				searing_cod = true
				fortressgrouper = true
				bonefish = true
				magmacubefish = true
				soulsucker = true

			[light_sources.settings.entities.nethersheep]
				atre = true

			[light_sources.settings.entities.biomeswevegone]
				man_o_war = true

			[light_sources.settings.entities.pescatore]
				minigame_fishing_bobber = true

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				furnace = true
				chest = true
				trapped_chest = true
				ender_chest = true
				jukebox = true
				dispenser = true
				dropper = true
				sign = true
				hanging_sign = true
				mob_spawner = true
				piston = true
				brewing_stand = true
				enchanting_table = true
				end_portal = true
				beacon = true
				skull = true
				daylight_detector = true
				hopper = true
				comparator = true
				banner = true
				structure_block = true
				end_gateway = true
				command_block = true
				shulker_box = true
				bed = true
				conduit = true
				barrel = true
				smoker = true
				blast_furnace = true
				lectern = true
				bell = true
				jigsaw = true
				campfire = true
				beehive = true
				sculk_sensor = true
				calibrated_sculk_sensor = true
				sculk_catalyst = true
				sculk_shrieker = true
				chiseled_bookshelf = true
				brushable_block = true
				decorated_pot = true

			[light_sources.settings.block_entities.doggomodoverhauled]
				dog_bowl_entity = true

			[light_sources.settings.block_entities.easyanvils]
				anvil = true

			[light_sources.settings.block_entities.easymagic]
				enchanting_table = true

			[light_sources.settings.block_entities.snowrealmagic]
				snow = true
				texture_tile = true

			[light_sources.settings.block_entities.therm]
				fireplace_block_entity = true

			[light_sources.settings.block_entities.visualworkbench]
				crafting_table = true

